#!/bin/bash

redshift -x
if [ -z "$1" ]
then
    xrandr --output HDMI-A-0 --brightness 0.6
else
    xrandr --output HDMI-A-0 --brightness $1
fi
redshift -O 4750
xrandr --output HDMI-A-0 --set TearFree on
